runtime: python39
entrypoint: gunicorn -b :$PORT kenyarentalhub_api.wsgi:application

instance_class: F2

env_variables:
  DJANGO_SECRET_KEY: 'your-secret-key'
  DJANGO_DEBUG: 'False'
  DJANGO_ALLOWED_HOSTS: 'your-app-id.uc.r.appspot.com'

handlers:
  - url: /static
    static_dir: static/
  - url: /media
    static_dir: media/
  - url: /.*
    script: auto
