# api/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView
from django.contrib.auth.views import LoginView  # Ensure LoginView is imported

from .views import RegisterView, MeView, PropertyViewSet, RentalApplicationViewSet
from .views import PaymentViewSet
from .views import ReviewViewSet
from django.contrib.auth.views import LogoutView


# Set up the DefaultRouter to automatically create routes for the viewsets
router = DefaultRouter()
router.register(r"properties", PropertyViewSet, basename="property")
router.register(r"applications", RentalApplicationViewSet, basename="application")
router.register(r"payments", PaymentViewSet, basename="payment")
router.register(r"reviews", ReviewViewSet, basename="review")

# URL patterns
urlpatterns = [
    # Auth routes for user registration, login, and token refresh
    path("auth/register/", RegisterView.as_view(), name="auth-register"),
    path("auth/login/", TokenObtainPairView.as_view(), name="auth-login"),
    path("auth/refresh/", TokenRefreshView.as_view(), name="auth-refresh"),
    path("auth/me/", MeView.as_view(), name="auth-me"),

    # Include all viewset routes generated by the router
    path("", include(router.urls)),

    # Custom login route for rendering the login page (Django's built-in LoginView)
    path('login/', LoginView.as_view(template_name='api/login.html'), name='login'),
]

